import Head from 'next/head'
import Image from 'next/image'
import Header from '../../../component/template/Header'
import Post from '../../../component/template/PostBox'
import Postar from '../../../component/template/Postar'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Darth Verde - Idéias para o Palmeiras</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header logotipo='Palmeiras' />
      
      <main className={styles.main}>
        <div className={styles.timeline}>
            <Postar />
            <Post big />
            <Post />
            <Post big/>
            <Post big />
            <Post />
            <Post big/>
            <Post big />
            <Post />
            <Post big/>
        </div>
        <div className={styles.sidebar}>
          <h1>Sidebar</h1>
        </div>
      </main>

      
    </div>
  )
}
